export type CLI_DETAILED_ERROR =
  | 'NO_CONTENT_IN_ADD'
  | 'NO_ID_IN_DONE'
  | 'INVALID_ID_IN_DONE'
  | 'NO_ID_IN_DELETE'
  | 'INVALID_ID_IN_DELETE'
  | 'NO_ID_IN_UPDATE'
  | 'INVALID_ID_IN_UPDATE'
  | 'INVALID_COMMAND';
